---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: instance_1
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    networks:
      - name: "acmenet"
        ipv4_address: '192.168.100.1'
#- name: instance_2
 #   image: docker.io/pycontribs/ubuntu:latest
  #  pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
